site_name: Hyperledger Fabric
site_url: http://hyperledger-fabric.readthedocs.io
theme: readthedocs
repo_url: https://github.com/hyperledger/fabric.git
site_description: 'Welcome to the Hyperledger fabric documentation'
strict: true
theme_dir: 'docs/custom_theme'

pages:
- Key Concepts:
  - Overview: overview.md
  - Why Fabric: whyfabric.md
  - Use Cases: biz/usecases.md
  - Glossary: glossary.md
  - Tx Data Model: data_model.md
  - Security Model: security_model.md
  - Multi Channel: multichannel.md
  - Smart Contracts: smartcontract.md
  - Consensus: consensus.md

- Getting Started:
  - The pieces: included.md
  - Setting up: asset_setup.md
  - Asset Transfer through SDK: asset_sdk.md
  - Using the CLI: asset_cli.md
  - Troubleshooting: asset_trouble.md

- Application Interfaces:
  - CLI: API/CLI.md
  - Node.js SDK: nodesdk.md
  - Java SDK: javasdk.md
  - Python SDK: pythonsdk.md

- Running Demos:
  - Marbles: marbles.md
  - Art Auction: auction.md
  - CP Paper: paper.md
  - Car Lease: carlease.md

- Tutorials:
  - Understanding chaincode basics: chaincode.md
  - Learn chaincode: learn_chaincode.md
  - Understanding docker compose: dockercompose.md
  - Sample application: sampleapp.md
  - Developer videos: videos.md
  - Administration and operations: adminops.md
  - Debugging: debug.md
  - Logging Control: Setup/logging-control.md

- Configuration Considerations:
  - Best Practices: recipes.md
  - Starting a network: bootstrap.md

- Architecture:
  - Overview: architecture.md
  - Deep dive: arch-deep-dive.md
  - Peer nodes:
    - Endorsers: endorser.md
    - Committers: committer.md
  - Policies & system chaincode: endorsement-policies.md
  - Ordering service: orderingservice.md
  - Pluggable implementations: pluggableos.md
  - Ledger: ledger.md
  - Gossip: gossip.md
  - Security & cryptography: Setup/ca-setup.md
  - Components: components.md
  - Transaction flow: txflow.md

- Getting Help:
  - Troubleshooting: troubleshooting.md
  - FAQs:
    - Architecture: FAQ/architecture_FAQ.md
    - Chaincode: FAQ/chaincode_FAQ.md
    - Confidentiality: FAQ/confidentiality_FAQ.md
    - Consensus: FAQ/consensus_FAQ.md
    - Identity: FAQ/identity_management_FAQ.md
    - Usage: FAQ/usage_FAQ.md

- Appendix:
  - Release notes: releases.md
  - Contributing: CONTRIBUTING.md
  - Development process and code:
    - Getting an account: Gerrit/lf-account.md
    - Maintainers: MAINTAINERS.md
    - Navigating JIRA: jira_navigation.md
    - Fabric developer setup: dev-setup/devenv.md
    - Building fabric: dev-setup/build.md
    - Gerrit: Gerrit/gerrit.md
    - Committing code: Gerrit/changes.md
    - Reviewing code: Gerrit/reviewing.md
    - Best practices: Gerrit/best-practices.md
    - Testing process: testing.md
  - Style Guides:
    - Golang: Style-guides/go-style.md
  - Still Have Questions?: questions.md
  - Criteria on quality: quality.md
  - Incubation notice: incubation.md
  - License: license.md

markdown_extensions:
  - toc:
     permalink: true
  - admonition
  - extra
  - tables
  - toc
  - fenced_code
  - smarty
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$
  - footnotes

copyright: Copyright &copy; 2017 IBM Corp. <br></br>Contributed to the Hyperledger Project under the <a href="https://github.com/hyperledger/fabric/blob/master/LICENSE" target="_blank">Apache Software License 2.0</a>
