site_name: Hyperledger Fabric
site_url: http://hyperledger-fabric.readthedocs.io
theme: readthedocs
repo_url: https://github.com/hyperledger/fabric.git
site_description: 'Welcome to the Hyperledger fabric documentation'
strict: true
theme_dir: 'docs/custom_theme'

pages:
- Introduction: 
  - Why Fabric: whyfabric.md
  - High Level Architecture: overview.md
  - Architectural Component Deep Dive: deepdive.md
  - Glossary: glossary.md
- Use Cases: usecases.md
- Quick Start: gettingstarted.md
- Releases: releases.md
- Chaincode Developer: 
  - Writing Chaincode: chaincodedev.md
  - Writing, Building, and Running Chaincode: Setup/Chaincode-setup.md
- Application Developer:  
  - CLI: API/CLI.md
  - Node Developer: node.md
  - Java Developer: java.md
- Contributing Developer:
  - v1.0 Preview: abstract_v1.md
  - Contributing: CONTRIBUTING.md
  - Maintainers: MAINTAINERS.md
  - Getting an Account: Gerrit/lf-account.md
  - Navigating Jira: jira_navigation.md
  - Fabric Developer Setup: dev-setup/devenv.md
  - Building Fabric: dev-setup/build.md
  - Gerrit: Gerrit/gerrit.md
  - Changes: Gerrit/changes.md
  - Reviewing: Gerrit/reviewing.md
  - Best Practices: Gerrit/best-practices.md
  - Canonical Use Cases: biz/usecases.md
  - Style Guides:
    - Golang: Style-guides/go-style.md
- Administration and Operations:
  - Debugging and Logging: Setup/logging-control.md
- Frequently Asked Question: faq.md
- Project Information: index.md

markdown_extensions:
  - toc:
     permalink: true
  - admonition
  - extra
  - tables
  - toc
  - fenced_code
  - smarty
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$
  - footnotes

copyright: Copyright &copy; 2017 IBM Corp. <br></br>Contributed to the Hyperledger Project under the <a href="https://github.com/hyperledger/fabric/blob/master/LICENSE" target="_blank">Apache Software License 2.0</a>
